apiVersion: v1
kind: Secret
metadata:
  name: axum-demo
  #namespace: development
type: Opaque
data:
  service_db_user: cG9zdGdyZXM=
  service_db_password: d2VsY29tZQ==
  service_token_duration_sec: MTgwMA==
