apiVersion: v1
kind: ConfigMap
metadata:
  name: axum-demo
  namespace: development
data:
  rust_log: "trace,sqlx::query=error,hyper=error,h2=error,tokio_util=error,tower=error,tonic=info"
  service_db_host: "postgres.development.svc.cluster.local"
  service_db_name: "app_db"
  service_db_port: "5432"
  app_host: "0.0.0.0"
  app_port: "8080"
  app_web_folder: "static/"
  jaeger_agent_host: "jaeger.development.svc.cluster.local"
  jaeger_agent_port: "4317"
  tracing_service_name: "axum-otpl"
  service_pwd_key: CKUGFOD9_2Qf6Pn3ZFRYgPYb8ht4vKqEG9PGMXTB7497bT0367DjoaD6ydFnEVaIRda0kKeBZVCT5Hb62m2sCA
  service_token_key: 9FoHBmkyxbgu_xFoQK7e0jz3RMNVJWgfvbVn712FBNH9LLaAWS3CS6Zpcg6RveiObvCUb6a2z-uAiLjhLh2igw
